// color palettes: triadic #A1A7CB, #CBA1A7, #A7CBA1
// 10 color objects of primary #2378c3 as generated by https://smart-swatch.netlify.app/#48bb78
// This is for reference purposes

export const COLOR = {
	50: "#e2fbed",
	100: "#c2ebd4",
	200: "#9fddb9",
	300: "#7ccf9e",
	400: "#58c184",
	500: "#3ea76a",
	600: "#2e8251",
	700: "#1f5d3a",
	800: "#0f3921",
	900: "#001506",
	borderColor: "#E7EAF3B2",
};
